### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#10]
## ❓ Contexte
Pour verrouiller l'accès à la plateforme, il est nécessaire de mettre en place de l'authentification

## 🧐 Objectifs
1. Mettre en place l'authentification
2. Initialiser des utilisateurs

## 💪 ToDo
- [x] Implémenter le tuto [(lien)](https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/)
- [x] Alimenter le yaml avec les utilisateurs
- [ ] Stocker le yaml sur un espace sécurisé
- [x] Tester l'appli

**Comment by KyllianBeguin** [comment]
Le tuto est déprécié, il faut aller sur [le repo de streamlit-authenticator](https://github.com/mkhorasani/Streamlit-Authenticator)

**Comment by KyllianBeguin** [comment]
## ✅ L'authentification est ON
On a deux utilisateurs, les autres sont à ajouter manuellement dans le fichier qui gère l'authentification.
Pour l'heure, pas d'autre moyen pour enregistrer un utilisateur, que de le mettre dans le fichier.

**Comment by KyllianBeguin** [comment]
On n'ira pas plus loin sur la sécurité.
