### ISSUE TITLE
setup production

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#12]
## ❓ Contexte
Pour déployer la plateforme, il faut mettre en place un environnement dédié.

## 🧐 Objectifs
1. Mettre en place de l'HTTPS

## 💪 ToDo
- [ ] Mettre en place Nginx
- [ ] Mettre en place le certificat let's encrypt dans Nginx
- [ ] Tester en local
- [ ] Tester sur la VM de prod

**Comment by KyllianBeguin** [comment]
~On va se servir de ce repo : https://github.com/joeychrys/streamlit_deployment/tree/main~

**Comment by KyllianBeguin** [comment]
Au final, on va partir sur nginx plutôt que traefik, plus simple à mettre en place.
Je vais maj le header de l'issue.
~Mise en place de nginx, cd ce tuto : https://dev.to/macelux/how-to-install-tlsssl-on-docker-nginx-container-with-lets-encrypt-34c5~ (cert auto signé = pas bon)

**Comment by KyllianBeguin** [comment]
Pour le nom de domaine, on va utiliser duck dns : https://www.duckdns.org/

**Comment by KyllianBeguin** [comment]
Tuto certbot + let's encrypt + nginx : https://phoenixnap.com/kb/letsencrypt-docker

**Comment by KyllianBeguin** [comment]
Pas de nginx ou autre. Pas d'HTTPS pour l'instant. Issue close
