### ISSUE TITLE
ONGLET - Data (Améliorations)

### ISSUE THREAD

**Issue by tgazagnes** [dataforgoodfr/12_zero_dechet_sauvage#22]
## ❓ Contexte
L'onglet Data est un des 4 onglets développés dans le dashboard Zéro Déchets Sauvages (Merterre). Des améliorations ont été demandées par Merterre.

## 🧐 Objectifs
1. Développer et recetter les évolutions de l'onglet demandées par Merterre
2. S'assurer de l'harmonisation entre les onglets

## 💪 ToDo
- [x] Définir avec Merterre les améliorations souhaitées
- [x] Développer et tester les améliorations
- [x] Valider avec Merterre & merger en staging

## 📁 Besoins métiers
La liste des améliorations souhaitées est disponible ici : https://merterre13.sharepoint.com/:w:/s/TeamMerTerre/EVUYy8bCNnJKiZJLdiYHqaUB1bMIhfUmxfL0j7-Msvi5Wg?rtime=OmwzvD563Eg

## 📁 Fichier
Votre fichier est celui-ci : [data.py](https://github.com/dataforgoodfr/12_zero_dechet_sauvage/blob/main/dashboards/app/pages/data.py)

### Pré-requis
- Avoir Docker sur votre machine - [DOC (Linux)](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) • [DOC post-installation (Linux)](https://docs.docker.com/engine/install/linux-postinstall/)
- Disposer d'un environnement virtuel Python - [DOC](https://docs.python.org/3/library/venv.html#creating-virtual-environments)
### Mise en place
1. Activer son environnement virtuel - (Linux) `source mon-venv/bin/activate`
2. Installer poetry - `python3 -m pip install "poetry==1.4.0"`
3. Installer les dépendances via poetry - `poetry install`
4. Installer les hooks pre-commit - `pre-commit install`
    * 🚨 Attention : vos commits ne seront pas push s'ils ne passent pas les hooks !
5. Aller dans le dossier `/dashboards`
6. Lancer l'infra Docker de développement - `docker compose -f docker-compose-dev.yml up --build`
    * 💡 Cela vous permettra de voir les logs du serveur en live, pendant que vous développez.
7. Votre environnement est prêt !
# 🔴🔴 IMPORTANT 🔴🔴
* Veuillez lancer `git pull` sur votre branche locale avant de commencer votre développement
    * Cela permet d'aller récupérer les modifications push par vos camarades
