### ISSUE TITLE
Mise en place de l'application de visualisation

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#3]
## ❓ Contexte
Pour anticiper la visualisation de données, nous allons mettre en place l'application de visualisation.

## 🧐 Objectifs
1. Avoir un moyen de livrer l'appli
2. Anticiper ce qu'il faut pour faire tourner l'appli

## 💪 ToDo
- [x] Initier un DockerFile
- [x] Mettre en place un environnement de dév (Dockerfile, docker-compose)
- [x] Alimenter le DockerFile avec tout ce qu'il faut pour le framework de visualisation
- [x] Tester l'image
- [x] Mettre en place les différents onglets

**Comment by KyllianBeguin** [comment]
La réunion du 14 mars a positionné la techno sur [Dash/Plotly](https://dash.plotly.com/)
👉 À prendre en compte pour l'initialisation de l'image

**Comment by KyllianBeguin** [comment]
On est presque good pour la mise en place de l'appli !
👉 J'ai ajouté de quoi permettre de dév et voir les changements en live : `Dockerfile-dev` et `docker-compose-dev.yml`. Le changement en live est permis grâce à un volume qui est consommé en continue par dash.
Les commandes pour :
* Lancer l'environnement de dév : ` docker compose -f docker-compose-dev.yml up --build`
  * Ne pas ajouter le flag `-d` pour pouvoir voir les logs de dash
* Lancer l'environnement de prod : `docker compose up -d`

**Comment by KyllianBeguin** [comment]
J'ai du mal à comprendre comment les onglets fonctionnent. Il y a bien le composant [dcc.Tabs](https://dash.plotly.com/dash-core-components/tabs) mais ça ne modifie qu'un graph, pas la page !
Edit : Trouvé ! Il faut pas chercher des onglets (tabs), mais des **pages** ! cf la [doc des apps multi-pages](https://dash.plotly.com/urls?_gl=1*1x2jzji*_ga*Mzg0OTkxNDkxLjE3MTA4NzUyNDA.*_ga_6G7EE0JNSC*MTcxMDg3NTI0MC4xLjAuMTcxMDg3NTI0NC41Ni4wLjA.)

**Comment by KyllianBeguin** [comment]
ON A DES PAGES !! 🥳

**Comment by KyllianBeguin** [comment]
Comme évoqué lors du point du 25/03/2024, on passe de dash à **streamlit** !
MaJ du commentaire en conséquence
