### ISSUE TITLE
ONGLET - Structures

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#4]
## ❓ Contexte
L'onglet Structures est un des 4 onglets prévus pour l'application et validés par Merterre. Son objectif est de répondre à la question : **Quels sont les acteurs impliqués sur mon territoire ?​**

A partir des analyses réalisées dans la phase d'exploration (cf #1), il faut maquetter et développer les visualisations correspondantes.

## 🧐 Objectifs
1. Conceptualiser l'onglet Structures
2. Développer l'onglet Structures 
3. S'assurer de l'harmonisation entre les onglets

## 💪 ToDo
- [x] Définir les indicateurs et analyses prioritaires à afficher sur l'onglet Structures
- [x] Réaliser une maquette de l'onglet Structures
- [x] Brancher les analyses sur la dernière version de la base de données
- [x] Développer les visualisations
- [x] Intégrer les visualisations dans le dashboard

## 📁 Fichier
Votre fichier est celui-ci : [structures.py](https://github.com/dataforgoodfr/12_zero_dechet_sauvage/blob/main/dashboards/app/pages/structures.py)

### Pré-requis
- Avoir Docker sur votre machine - [DOC (Linux)](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) • [DOC post-installation (Linux)](https://docs.docker.com/engine/install/linux-postinstall/)
- Disposer d'un environnement virtuel Python - [DOC](https://docs.python.org/3/library/venv.html#creating-virtual-environments)
### Mise en place
1. Activer son environnement virtuel - (Linux) `source mon-venv/bin/activate`
2. Installer poetry - `python3 -m pip install "poetry==1.4.0"`
3. Installer les dépendances via poetry - `poetry install`
4. Installer les hooks pre-commit - `pre-commit install`
    * 🚨 Attention : vos commits ne seront pas push s'ils ne passent pas les hooks !
5. Aller dans le dossier `/dashboards`
6. Lancer l'infra Docker de développement - `docker compose -f docker-compose-dev.yml up --build`
    * 💡 Cela vous permettra de voir les logs du serveur en live, pendant que vous développez.
7. Votre environnement est prêt !

# 🔴🔴 IMPORTANT 🔴🔴
* Veuillez lancer `git pull` sur votre branche locale avant de commencer votre développement
    * Cela permet d'aller récupérer les modifications push par vos camarades
