### ISSUE TITLE
ONGLET - Actions

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#5]
## ❓ Contexte
L'onglet Actions est un des 4 onglets prévus pour l'application et validés par Merterre. Son objectif est de répondre à la question : **Quelles actions sont mises en place par ces acteurs ?​**

A partir des analyses réalisées dans la phase d'exploration (cf #1), il faut maquetter et développer les visualisations correspondantes.

## 🧐 Objectifs
1. Conceptualiser l'onglet Actions
2. Développer l'onglet Actions 
3. S'assurer de l'harmonisation entre les onglets

## 💪 ToDo
- [x] Définir les indicateurs et analyses prioritaires à afficher sur l'onglet Actions
- [x] Réaliser une maquette de l'onglet Actions
- [x] Brancher les analyses sur la dernière version de la base de données
- [x] Développer les visualisations
- [x] Intégrer les visualisations dans le dashboard

## 📁 Fichier
Votre fichier est celui-ci : [actions.py](https://github.com/dataforgoodfr/12_zero_dechet_sauvage/blob/main/dashboards/app/pages/actions.py)

### Pré-requis
- Avoir Docker sur votre machine - [DOC (Linux)](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) • [DOC post-installation (Linux)](https://docs.docker.com/engine/install/linux-postinstall/)
- Disposer d'un environnement virtuel Python - [DOC](https://docs.python.org/3/library/venv.html#creating-virtual-environments)
### Mise en place
1. Activer son environnement virtuel - (Linux) `source mon-venv/bin/activate`
2. Installer poetry - `python3 -m pip install "poetry==1.4.0"`
3. Installer les dépendances via poetry - `poetry install`
4. Installer les hooks pre-commit - `pre-commit install`
    * 🚨 Attention : vos commits ne seront pas push s'ils ne passent pas les hooks !
5. Aller dans le dossier `/dashboards`
6. Lancer l'infra Docker de développement - `docker compose -f docker-compose-dev.yml up --build`
    * 💡 Cela vous permettra de voir les logs du serveur en live, pendant que vous développez.
7. Votre environnement est prêt !

# 🔴🔴 IMPORTANT 🔴🔴
* Veuillez lancer `git pull` sur votre branche locale avant de commencer votre développement
    * Cela permet d'aller récupérer les modifications push par vos camarades

**Comment by Mendi33** [comment]
Je viens de faire un commit pour notre onglet avec Valérie et Vincent.

J'ai copié collé le home.py de l'onglet DATA pour que Valérie ai accès aux filtres administratifs et collectivité.

J'ai modifié le requierements.txt pour ajouter folium et plotly (memes versions que l'onglet DATA (respectivement 0.15.1 et 5.19.0)

Actions.py contient notre travail à Valerie et moi:

- 1er onglet pour les événements passés : en cours de développement par Valérie et Vincent en renfort. 
J'ai collé le code de Valérie pour que Vincent y ai accès

- Dans le 2eme onglet, les evenements a venir : presque fini, il ne me reste qu'a réduire la taille des container de la liste des événements. 
Ainsi que mettre en forme la popup des markers de la map.

Ouvert aux suggestions/modifications/critiques sur l'onglet Evenements a venir.

On vous tiens au courant quant à l'avancée de l'onglet Evenement passés

**Comment by Mendi33** [comment]
Hello, 
@KyllianBeguin 
Je voulais faire un push des derniers changements sur l'onglet Actions (changement disposition dans "événements à venir", derniers graphs ajoutés aux "événements", etc)

J'ai fait un pull, relancer l'infra Docker pour prendre en compte les changements de requierements.txt  (depuis le commit "Add authentification") mais maintenant j'ai l'erreur suivante : 

```
[Errno 2] No such file or directory: '.credentials.yml'

File "/zds/home.py", line 28, in <module>
    with p_cred.open() as file:
         ^^^^^^^^^^^^^
```

**Comment by Mendi33** [comment]
Je viens de faire le last push avant de pull Request :

**requierements.txt :** 
Ajout de "Babel==2.11.0" - Package pour afficher les dates en FR sans changer la variable locale.

### Corrections demandés par Teo réalisées: 
**action.py :**
- Nouvelle emoji pour la page et les 2 onglets
- Remplacement de la ligne de sous-titres 
- Toutes les mois des dates s'affichent en francais

**Onglet 1 :** 
- Filtre période “toute la période” au lieu de “aucune sélection”
- Titre du sous onglet : “événements” > “ramassages réalisés” 
- Filtre par années pas dans l’ordre : proposer par ordre chronologique inverse  (2024 en 1er)
- Filtre temporel plus précis ? 
Ajout d'un filtre mois qui s'affiche seulement quand une année est sélectionnée
- Bouton “Nombre de structures”, mettre “nombre de structures participantes”
- Diminuer la taille du plus grand point
Facteur passé de 100 à 200
- Relevés par types de milieux : trop étroit 
Dépend de la taille de l’écran de l'utilisateur, mais les textes entre parenthèses  a été enlevé pour une meilleur lisibilité et un meilleur affichage
- Niveaux de caractérisation “0, 1, 2, 3, 4” à remettre dans l’ordre
- Code couleur niveaux de carac : rester sur du bleu de claire (niveaux 0) à foncé (niveaux 4)  
Bleu foncé pour le niveau 0, le plus clair pour le 4 
- Garder à chaque fois le même nombre de chiffre significatif (arrondi à l’unité) 
- Ajout d'un 5eme graphique : Nb evenements par type de Lieu
