### ISSUE TITLE
ONGLET - Hotspots

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#6]
## ❓ Contexte
L'onglet Hotspots est un des 4 onglets prévus pour l'application et validés par Merterre. Son objectif est de répondre à la question : **Quelles sont les zones les plus impactées ?​**

A partir des analyses réalisées dans la phase d'exploration (cf #1), il faut maquetter et développer les visualisations correspondantes.

## 🧐 Objectifs
1. Conceptualiser l'onglet Hotspots
2. Développer l'onglet Hotspots 
3. S'assurer de l'harmonisation entre les onglets

## 💪 ToDo
- [x] Définir les indicateurs et analyses prioritaires à afficher sur l'onglet Hotspots
- [x] Réaliser une maquette de l'onglet Hotspots
- [x] Brancher les analyses sur la dernière version de la base de données
- [x] Développer les visualisations
- [x] Intégrer les visualisations dans le dashboard

## 📁 Fichier
Votre fichier est celui-ci : [hotspots.py](https://github.com/dataforgoodfr/12_zero_dechet_sauvage/blob/main/dashboards/app/pages/hotspots.py)

### Pré-requis
- Avoir Docker sur votre machine - [DOC (Linux)](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) • [DOC post-installation (Linux)](https://docs.docker.com/engine/install/linux-postinstall/)
- Disposer d'un environnement virtuel Python - [DOC](https://docs.python.org/3/library/venv.html#creating-virtual-environments)
### Mise en place
1. Activer son environnement virtuel - (Linux) `source mon-venv/bin/activate`
2. Installer poetry - `python3 -m pip install "poetry==1.4.0"`
3. Installer les dépendances via poetry - `poetry install`
4. Installer les hooks pre-commit - `pre-commit install`
    * 🚨 Attention : vos commits ne seront pas push s'ils ne passent pas les hooks !
5. Aller dans le dossier `/dashboards`
6. Lancer l'infra Docker de développement - `docker compose -f docker-compose-dev.yml up --build`
    * 💡 Cela vous permettra de voir les logs du serveur en live, pendant que vous développez.
7. Votre environnement est prêt !

# 🔴🔴 IMPORTANT 🔴🔴
* Veuillez lancer `git pull` sur votre branche locale avant de commencer votre développement
    * Cela permet d'aller récupérer les modifications push par vos camarades

**Comment by KyllianBeguin** [comment]
Hello !
Je constate que cette issue n'est pas très active. Pensez à indiquer ce sur quoi vous avez avancé, cela sera plus agréable à lire que des messages de commits :)

Aussi, j'en profite pour vous ajouter openpyxl dans les requirements, puisqu'il est nécessaire pour lire les fichiers excel `releves_corrects_surf_lineaire.xlsx` et `export_structures_29022024.xlsx`

**Comment by KyllianBeguin** [comment]
Je vous invite aussi à échanger sur votre onglet avec @Vincentdata @tgazagnes. J'ai le sentiment qu'une grande partie de ce que vous avez développé et déjà présent dans d'autres parties de l'app. Par exemple, le filtre est dans le `home.py`

Je peux vous merge le **staging** vers votre branche pour vous intégrer l'authent'' ainsi que ce les filtres et autres fonctionnalités que j'ai du zappé. @linh-dinh-1012 @DridrM je vous laisse préparer le terrain pour faciliter le merge (Virer les filtres du `hotspots.py` etc...)

**Comment by linh-dinh-1012** [comment]
Bonsoir @KyllianBeguin,
Merci pour ton message. @Vincentdata nous a déjà informés de ce problème dans un message et @DridrM est en train de s'en occuper.
Cependant, il est vrai que nous avons un filtre sur les régions qui pourrait potentiellement être remplacé par celui dans home.py. À part ça, les autres filtres sont différents et essentiels pour nos graphs, comme tu peux le voir dans la capture d'écran ci-dessous. Nous faisons de notre mieux pour faciliter le merge.
![image](https://github.com/dataforgoodfr/12_zero_dechet_sauvage/assets/147145870/950b658a-0bae-4d72-a1db-e212651672d2)

**Comment by KyllianBeguin** [comment]
~Je vais vous cherry-pick les changements du `home.py` du staging dans votre branche.
Vous aurez l'authent + les filtres~
Edit : vous avez déjà les changements

**Comment by KyllianBeguin** [comment]
Hello !
Y a un petit soucis avec la carte je crois. Lors d'un dezoom, elle disparait.

**Comment by linh-dinh-1012** [comment]
Salut Kyllian,
Merci pour ton retour. Je viens de pusher le fichier hotspots.py corrigé. Pourrais-tu vérifier s'il marche cette fois? 

Cf #20
