### ISSUE TITLE
ONGLET - Data

### ISSUE THREAD

**Issue by KyllianBeguin** [dataforgoodfr/12_zero_dechet_sauvage#7]
## ❓ Contexte
L'onglet Data est un des 4 onglets prévus pour l'application et validés par Merterre. Son objectif est de répondre à la question : **Quels impacts sur les milieux naturels et quels sont les comportements/ usages / Secteurs economiques à l’origine de cette pollution / macrodechets ?​**

A partir des analyses réalisées dans la phase d'exploration (cf #1), il faut maquetter et développer les visualisations correspondantes.

## 🧐 Objectifs
1. Conceptualiser l'onglet Data
2. Développer l'onglet Data 
3. S'assurer de l'harmonisation entre les onglets

## 💪 ToDo
- [x] Définir les indicateurs et analyses prioritaires à afficher sur l'onglet Data
- [x] Réaliser une maquette de l'onglet Data
- [x] Brancher les analyses sur la dernière version de la base de données
- [x] Développer les visualisations
- [x] Développer l'onglet Streamlit & intégrer les visualisations dans le dashboard

## 📁 Fichier
Votre fichier est celui-ci : [data.py](https://github.com/dataforgoodfr/12_zero_dechet_sauvage/blob/main/dashboards/app/pages/data.py)

### Pré-requis
- Avoir Docker sur votre machine - [DOC (Linux)](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) • [DOC post-installation (Linux)](https://docs.docker.com/engine/install/linux-postinstall/)
- Disposer d'un environnement virtuel Python - [DOC](https://docs.python.org/3/library/venv.html#creating-virtual-environments)
### Mise en place
1. Activer son environnement virtuel - (Linux) `source mon-venv/bin/activate`
2. Installer poetry - `python3 -m pip install "poetry==1.4.0"`
3. Installer les dépendances via poetry - `poetry install`
4. Installer les hooks pre-commit - `pre-commit install`
    * 🚨 Attention : vos commits ne seront pas push s'ils ne passent pas les hooks !
5. Aller dans le dossier `/dashboards`
6. Lancer l'infra Docker de développement - `docker compose -f docker-compose-dev.yml up --build`
    * 💡 Cela vous permettra de voir les logs du serveur en live, pendant que vous développez.
7. Votre environnement est prêt !
# 🔴🔴 IMPORTANT 🔴🔴
* Veuillez lancer `git pull` sur votre branche locale avant de commencer votre développement
    * Cela permet d'aller récupérer les modifications push par vos camarades

**Comment by tgazagnes** [comment]
Questions à discuter avec Merterre le 27/03 :
- Choix des indicateurs et visualisations pour l'onglet DATA, sur la base de la proposition de Vincent & Thibaut
    - Secteurs & filières REP : n'en garder qu'un sur les 2 ? (info redondante)
    - Nombre de déchets à afficher à partir des colonnes GROUPE et non DCSMM (hypothèse à confirmer : les données collectées au niveau 4 sont également comptées dans les colonnes GROUPE) 
    - Visualisation cartographique : quels besoins ?
- Filtres automatiques à prévoir à l'ouverture de l'onglet ? 
    - Année : par ex : afficher les données de l'année N-1 par défaut
    - Territoire

**Comment by tgazagnes** [comment]
Notes de l'échange Quentin-Téo-Vincent-Thibaut (27/03):
- Retour sur la maquette : onglet Matériaux
    - [x] bien reprendre les couleurs par matériaux (charte graphique sur le sharepoint)
    - [x] Aller du plus global au plus détaillé : KPI puis graphe global tous milieux confondus, ensuite les filtres
    - [x] KPI Nombre d'objets : à déplacer sur l'onglet Caractérisation des déchets
    - [x] Donut par matériau : ajouter la catégorie AUTRES
    - [x] Filtrer sur les relevés dont la part de AUTRES est inférieure à 20% ou inférieure à 500L, pour éviter que la catégorie AUTRES ne soit prédominante. Appliquer ce filtre sur toute la page & afficher en haut ("ces stats se basent sur XXX de ramassages")
    - [ ] KPI globaux : ajouter le volume pris en compte dans les stats
    - [x] Ne pas se limiter à une année mais prendre tous les relevés et avoir un filtre par année
    - [ ] Graphe par milieux : afficher uniquement les milieux avec au moins 5 relevés. Mais il faut mettre le paramètre en variable pour que les users avertis puissent le modifier (par ex : petites communes sur lesquels il y a peu de relevés)
    - [x] Volume par matériaux : garder le même donut
    - [ ] Ordre des filtres : Milieu / Lieu / Année
    - [x] remettre les 2 chiffres qu'il y avait en haut
- Onglet Caractérisation des déchets : 
    - [x] prendre uniquement les variables GROUPE qui incluent tous les relevés n2-3-4
    - [x] possibilité d'appliquer couleurs matériaux aux déchets (charte graphique) ? avec tableau de correspondance déchets-matériaux sur les barres
 - Onglet Typologie : trop détaillé pour les collectivités
    - [x] pour l'instant on oublie cet onglet pour simplifier
    - [ ] on rajoute l'analyse fine des déchets niveau 4 à la fin de l'onglet Caractérisation
 - Onglet Secteurs & filièrs REP & marques 
     - [x] filtres milieu, lieu année
     - [x] graphe secteurs
     - [x] graphe rep
     - [x] graphe marques
- [ ] Sur chaque onglet / analyse : avoir le nombre de déchets et de relevés compris dans les analyses

**Comment by Vincentdata** [comment]
- Thibault gazagnes a commencé à coder le dashboard sur le fichier data.py : definition des differents onglets , positionnement des premiers graphiques sur le premier et second onglet

- Vincent MARTIN : ajout du graph top 10 dechets barplot et les metrics, ajout de la carte avec selection du dechet dans la liste top 10, préparation des dictionnaires pour application des filtres, creation d'un fichier style.css et ajout de librairies dans requirements.txt

**Comment by faouzihakimi** [comment]
- Ajout dans l'onglet caractérisation des déchets des chiffres clés.  
- Mise à l'échelle log du graphique 'top 10 déchets'. 
- Mise à jour du fichier requirements.txt

**Comment by faouzihakimi** [comment]
- Première version du sous onglet 'secteurs et marques'.
- Changements mineurs.

**Comment by Vincentdata** [comment]
- Caching de la fonction de download des données pour limiter la latence
- Ajout des filtres année milieu et lieu sur le sous onglet secteurs et marques et la seconde partie du sous onglet materiau 
- Ajout des couleurs sur le barplot top dechets selon les materiaux (code couleur charte graphique merterre)

**Comment by tgazagnes** [comment]
- filtres niveaux admin (région, dép) et collectivité ajoutés sur l'onglet home (en entrée du dashboard)
- enregistrement du dataframe filtré sur la collectivité dans un st.session.state pour pouvoir le conserver entre les onglets
- mise à jour des filtres dans l'onglet data/matériaux

**Comment by Vincentdata** [comment]
Sous onglet materiau
- Ajout des metrics apres filtration
- correction des filtres

**Comment by faouzihakimi** [comment]
- proposition de graphique alternatif (top 10 déchets) pour le sous onglet "matériaux"
- ajout des couleurs aux graphes du sous-onglet "secteurs et marques"
- modifications mineures

**Comment by tgazagnes** [comment]
- ajout de la persistence des filtres dans la page Home.py. Les valeurs des filtres sélectionnées sont conservées entre les onglets et si l'on revient changer la sélection. L'option "st.form" n'était pas judicieuse finalement, elle ne permet pas de mettre à jour la liste dans une selectbox en fonction du filtre précédent.
- Retrait du package streamlit-dynamic-filters dans les requirements (plus utilisé)

**Comment by tgazagnes** [comment]
> * proposition de graphique alternatif (top 10 déchets) pour le sous onglet "matériaux"
> 
>     * ajout des couleurs aux graphes du sous-onglet "secteurs et marques"
> 
>     * modifications mineures

C'est top ! quelques suggestions : 
- Peut-on essayer de mettre les filtres dans un st.popover ou un encart plus petit ? Ils prennent beaucoup de place en haut
- La légende du graphique des secteurs n'est pas utile, puisque chaque secteur a 1 seule couleur possible. On peut l'enlever pour plus de lisibilité
- Dans le graphique par marques, la légende devrait plutôt se rapporter au secteur ?
- Je trouve les metrics du nombre de secteurs et du nombre de marques peu parlantes (ça change pas grand chose d'avoir 20 ou 50 marques représentées) donc je suggère de ne garder que 2 ou 3 metrics en haut de page avec les volumes catégorisés par exemple. (à discuter demain avec Merterre)

**Comment by tgazagnes** [comment]
16/4 :
- Remontée du filtre sur df_nb_dechets en page Home, au moment de la sélectin du niveau géographique
- Corrections mineures sur le calcul des metrics
- Ajout de la métrique 'nb total de déchets' dans l'onglet Top Déchets
- Modifs mineures sur les légendes et les étiquettes des graphs

**Comment by KyllianBeguin** [comment]
Salut l'équipe onglet-Data
@faouzihakimi j'ai vu que tu avais renommé le Dockerfile en dockerfile. cf 24aea8f
Pouvez-vous rétablir le nom du fichier ?

### 👮‍♂️ Je vous demande, si possible, de ne pas toucher à la configuration (dockerfiles, docker-compose).

**Comment by tgazagnes** [comment]
Todo suite revue avec Téo, Vincent et Faouzi :
Onglet matériaux :
- [x] Garder le treemap en bas à la place du donut
- [x] Ajouter un message si on a moins de 5 collectes (plutôt qu'un filtre)
- [x] Agrandir la police dans le treemap
- [x] Répartition par matériau : Mettre labels en diagonale 
- [ ] retrait des "hover labels" sur le donut et barplot du haut de l onglet matériau => je trouve que ça reste utile sur le donut pour voir la légende et le volume associé...

Top 10 déchets :
- [x] Garder l’alternative  : bar chart en horizontal
- [x] Enlever le tableau à droite et les colonnes
- [x] Mettre la légende en bas à droite pour ne pas prendre sur la taille du graphique
- [x] Cartographie : augmenter la taille des points

Sous-onglet nb_dechets
- [x] Enlever les valeurs « indeterminés » et « vide » : voir avec le retour de Téo/Quentin
- [x] Mettre le nb de collectes dans les metrics
- [ ] Secteur économique vide : déchets autres qui ne sont pas dans la base
- [x] Enlever les couleurs pour les marques (pas besoin de légende) 
- [x] Enlever les légendes
- [x] Ajouter la marque et le chiffre dans les barres

+ demandes Téo et Quentin : 
Teo Juricev
- [ ]Hello ! Pour la question des secteurs éco "vide" et "indéterminé", est-ce qu'il y a moyen d'avoir un bouton pour les faire apparaître ou non?
Aussi, si on ne les fait pas apparaître, afficher une phrase du type "il y a X % de déchets dont le secteur économique n'a pas pu être déterminé"
- [ ]Dans tous les cas, il faudra agréger les deux catégories !

- [x] Pour le graph marques, pour les couleurs, vous pouvez tenter les couleurs :
ZDS : #003463 ou #E9003F
MerTerre : #1951A0
On vous fait confiance pour choisir ce qui rend le mieux :clin_d'œil:

**Comment by KyllianBeguin** [comment]
Bon petit soucis avec votre PR.
Y a des merges conflits partout à cause de l'ajout de l'authentification... Causés principalement par l'ajout de tabulations, mais comme vous avez ajouté des changements au fichier de base que j'ai utilisé pour mettre en place l'authent', bah ça fout la merde 😥
~Je fais merge le staging chez vous.~
Je vais push l'authent' sur votre home.py et data.py

**Comment by tgazagnes** [comment]
Rappel todo suite point avec Téo du 23/04
Général
- [ ] Harmoniser les sous-titres des différents onglets
- [ ] Harmoniser la position et la mention du territoire "département ..."
- [x] si possible, diminuer la taille des Metrics (update : pas possible sauf modification complexe en CSS)
- [x] remplacer "part..." par "proportion"
- [x] Filtre par année : ordre antéchronologique (plus récents en premier)
- [x] Harmoniser police dans les graphs : 13 ou 14 pour l'affichage
- [x] Metrics : lorsque les chiffres sont grands, essayer une présentation plus lisible (tester humanize = Thibaut)
Sous onglet matériaux
- [x] Changer légende : Papier et Carton / Verre et Céramique
- [x] dans les labels du graphe par millieu, enlever les parties qui sont entre parenthèses pour gagner de la place

Sous-onglet Top10 déchets
- [ ] possible de mettre d'autres déchets que le top 10 ? si ça ne dégrade pas la lisibilité
- [x] Légende remontée au dessus du graphique 
Sous-onglets Secteurs marques
- [x] Titre du graph : "Top 10 des secteurs économiques attribués aux déchets catégorisés"
- [ ] Ajouter le % de chaque secteur dans la barre ou dans la hover label (% calculé sur le TOTAL catégorisé EXCEPTE indeterminé ou vide) + ajouter message avec le nb et % d'indéterminé ou vide
- [x] Graph par marque : enlever la décimale
- [x] Manque accent dans le titre du graph
- [x] garder secteurs et marques en barplot et treemap pour responsabilités
